# URLs BB Developers ? Homologacao (Teste)
# OAuth:    https://oauth.hm.bb.com.br/oauth/token
# Pix:      https://api.hm.bb.com.br/pix/v2
# Cobranca: https://api.hm.bb.com.br/cobrancas/v2
# Extrato:  https://extratos.mtls.api.hm.bb.com.br/v2 (mTLS)

bb.oauth-url=https://oauth.hm.bb.com.br/oauth/token
bb.pix-base-url=https://api.hm.bb.com.br/pix/v2
bb.pix-requer-mtls=false
bb.cobranca-base-url=https://api.hm.bb.com.br/cobrancas/v2
bb.extrato-base-url=https://extratos.mtls.api.hm.bb.com.br/v2
bb.extrato-homologacao-header=178961031

bb.wiretap-enabled=true
logging.level.reactor.netty.http.client.HttpClient=DEBUG
