# URLs BB Developers ? Producao
# OAuth:    https://oauth.bb.com.br/oauth/token
# Pix producao exige mTLS: https://api-pix.bb.com.br/pix/v2
# Cobranca: https://api.bb.com.br/cobrancas/v2
# Extrato:  https://extratos.mtls.api.bb.com.br/v2 (mTLS)

bb.oauth-url=https://oauth.bb.com.br/oauth/token
bb.pix-base-url=https://api-pix.bb.com.br/pix/v2
bb.pix-requer-mtls=true
bb.cobranca-base-url=https://api.bb.com.br/cobrancas/v2
bb.extrato-base-url=https://extratos.mtls.api.bb.com.br/v2
bb.extrato-homologacao-header=

bb.wiretap-enabled=false
