spring.application.name=BBDeveloper

# BB Developer OAuth
bb.client-id=eyJpZCI6IjNmZGFhNzMtYjhiYS00MzcyLTliNzEtMSIsImNvZGlnb1B1YmxpY2Fkb3IiOjAsImNvZGlnb1NvZnR3YXJlIjoxOTA3NTgsInNlcXVlbmNpYWxJbnN0YWxhY2FvIjoxfQ
bb.client-secret=
bb.developer-key=
bb.oauth-url=
bb.pix-base-url=
bb.cobranca-base-url=
bb.extrato-base-url=
bb.extrato-homologacao-header=
bb.scope=

# Certificado mTLS
bb.ssl-cert-path=
bb.ssl-cert-password=

bb.pix-key=